package com.citi.developerhub.sandbox.kotlinstarter

data class Data(val fixedHeightSmallWidth: String = "",
                val fixedWidthDownsampledHeight: String = "",
                val caption: String = "",
                val type: String = "",
                val imageHeight: String = "",
                val fixedHeightDownsampledHeight: String = "",
                val fixedHeightSmallStillUrl: String = "",
                val id: String = "",
                val fixedWidthSmallWidth: String = "",
                val imageUrl: String = "",
                val imageFrames: String = "",
                val imageMpUrl: String = "",
                val fixedHeightDownsampledWidth: String = "",
                val imageWidth: String = "",
                val url: String = "",
                val imageOriginalUrl: String = "",
                val fixedWidthDownsampledUrl: String = "",
                val fixedWidthDownsampledWidth: String = "",
                val fixedHeightSmallHeight: String = "",
                val fixedHeightDownsampledUrl: String = "",
                val fixedWidthSmallStillUrl: String = "",
                val fixedWidthSmallHeight: String = "",
                val fixedHeightSmallUrl: String = "",
                val fixedWidthSmallUrl: String = "",
                val username: String = "")